version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=hans
      - POSTGRES_PASSWORD=242312359hH
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: